image: gbraad/godot-server:2.1.4
stages:
  - build

build:linux:
  stage: build
  script:
    - mkdir -p public/linux
    - godot -export_debug "Linux X11" public/linux/game
  only:
    - master
  artifacts:
    paths:
      - public

build:windows:
  stage: build
  script:
    - mkdir -p public/windows
    - godot -export_debug "Windows Desktop" public/windows/game.exe
  only:
    - master
  artifacts:
    paths:
      - public

