image: gbraad/godot-server:2.1.4
stages:
  - build

build:linux:
  stage: build
  script:
    - godot -export_debug "Linux X11" game
  only:
    - master

build:windows:
  stage: build
  script:
    - godot -export_debug "Windows Desktop" game.exe
  only:
    - master

